slam_toolbox:
  ros__parameters:
    use_sim_time: false
    odom_frame: /odom
    map_frame: map
    base_frame: /base_footprint
    map_file_name: "/common/ros_launcher/launch_slam_toolbox/bld10_4F"
    resolution: 0.05
    mode: "localization"
    scan_topic: "/scan"
    publish_pose: true
    pose_topic: "/pose"
    map_start_pose: [0.0, 0.0, 0.0]
    localization_mode: true
    map_update_interval: 1.0
    transform_publish_period: 0.05
    map_publish_period: 1.0