slam_toolbox:
  ros__parameters:
    use_sim_time: false
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    map_file_name: ""
    resolution: 0.1
    mode: "mapping"
    map_start_pose: [0.0, 0.0, 0.0]
    scan_topic: "/scan"
    transform_publish_period: 0.02 #if 0 never publishes odometry
    use_scan_matching: true
    map_update_interval: 10.0
    distance_variance_penalty: 1.0
    angle_variance_penalty: 3.0
    loop_search_maximum_distance: 3.0
    do_loop_closing: true 
    loop_match_minimum_chain_size: 10           
    loop_match_maximum_variance_coarse: 3.0  
    loop_match_minimum_response_coarse: 0.35    
    loop_match_minimum_response_fine: 0.45