ARG BASE_IMAGE
ARG ROS_PACKAGE
ARG SEPARATE
ARG ROS_DISTRO
FROM ${BASE_IMAGE} as base

SHELL [ "/bin/bash","-c" ]

WORKDIR /usr/src


RUN wget -O install_pivariety_pkgs.sh https://github.com/ArduCAM/Arducam-Pivariety-V4L2-Driver/releases/download/install_script/install_pivariety_pkgs.sh\
  && chmod +x install_pivariety_pkgs.sh\
  && ./install_pivariety_pkgs.sh -p libcamera_dev\
  && ./install_pivariety_pkgs.sh -p libcamera_apps
