ARG BASE_IMAGE
ARG ROS_PACKAGE
ARG SEPARATE
ARG ROS_DISTRO
FROM ${BASE_IMAGE} as base

SHELL [ "/bin/bash","-c" ]

RUN apt update \
  && apt install -y ros-${ROS_DISTRO}-vrpn-mocap \
  && apt autoremove -y \
  && rm -rf /var/lib/apt/lists/*
